### ISSUE TITLE
Yaar Bhai Aap Ki Choti Se Madad Chahie... 

### ISSUE THREAD

**Issue by graysuit** [SherazIbrahim/Psd-Rat-#2]
### Assalam u Allikum bhai @**SherazIbrahim**,
Jesa K aap **programmer** ho, 
Main bhi aik **programmer** hoo, Aap chaho to meri bhi **respositories** daikh sakte ho,
Lekin aap **senior** ho, Es lie **madad** maang raha hoo...

Aik chota sa koi **Visual basic** Ya **C#** Ya **C++** ka aesa code likho,
Jo https://files.000webhost.com/ ke account main login kre,
Aur aik **text** file ko **upload** kre. 
Advance main shukeria...

**Comment by SherazIbrahim** [comment]
Ye program merey pas maujood hi

**Comment by SherazIbrahim** [comment]
Is k liay ap ko ftp protocol use karna hi

**Comment by graysuit** [comment]
Han Yaar,
Jo bhi ho, Bus code de do,
ftp protocol ke lie aap ke khial se konsi free web hosting achi hai ???

Kuch to ye hain jo main estemaal kerta hoo::::::

- http://000webhost.com
- http://freeweb.pk
